# https://taskfile.dev

version: '3'
tasks:
  pre-reqs:
    - python3 -m pip install --upgrade pip
    - sudo apt install hugo git -y
    - pip install --no-input pre-commit mdformat-gfm mdformat-frontmatter
    # - pre-commit install
  default:
    cmds:
      # - mdformat content
      - git submodule update --init --recursive --remote
      - hugo server -D --disableFastRender --enableGitInfo
    silent: false
